version: "3.8"

services:
  backend:
    build: .
    container_name: fittrack-backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql
    networks:
      - fittrack_net

  mysql:
    image: mysql:8
    container_name: fittrack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - fittrack_net

  nginx:
    image: nginx:alpine
    container_name: fittrack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - fittrack_net

volumes:
  mysql_data:

networks:
  fittrack_net:
    driver: bridge

